# Generated by Django 5.1.4 on 2025-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("original_language", models.CharField(max_length=10)),
                ("number_of_seasons", models.PositiveIntegerField()),
                ("number_of_episodes", models.PositiveIntegerField()),
                ("first_air_date", models.DateField(blank=True, null=True)),
                ("last_air_date", models.DateField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
