# Generated by Django 5.1.4 on 2025-06-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVShowGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.genre"
                    ),
                ),
                (
                    "tvshow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.tvshow"
                    ),
                ),
            ],
            options={
                "unique_together": {("tvshow", "genre")},
            },
        ),
    ]
