# Generated by Django 5.1.4 on 2025-07-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.CreateModel(
            name="TVShowCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.country",
                    ),
                ),
                (
                    "tvshow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.tvshow"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TV Show Countries",
                "unique_together": {("tvshow", "country")},
            },
        ),
    ]
