# Generated by Django 5.1.4 on 2026-05-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_country_options_tvshowcountry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tvshow",
            options={"verbose_name_plural": "TV Shows"},
        ),
        migrations.AlterModelOptions(
            name="tvshowgenre",
            options={"verbose_name_plural": "TV Show Genres"},
        ),
    ]
